added db credential support vor evelon module
Yggdrasil-Worlds/DAL pull request #15
Opened 2024-03-15 21:09 UTC by Invincible2211

2024-03-17 09:20 UTC, Morazzer requested changes

2024-03-17 09:20 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/strings/logging/DatabaseConnectionLogger.java
> +public interface DatabaseConnectionLogger {
This doesn't fit the class naming scheme for the package

2024-03-17 11:43 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/DAL.java
> +        Dotenv dotenv = Dotenv.configure().load();
Also is the extra library really required to read a file?

2024-03-17 14:32 UTC, Invincible2211 commented on src/main/java/de/yggdrasil/core/dal/DAL.java
> +        Dotenv dotenv = Dotenv.configure().load();
In my opinion, it's unnecessary to write this function on my own when there is already a library for this exact purpose. To read this file, I could also use a file reader, but then I would have to check which value I read, or I would need to require a certain environment variable in a specific line (which is not good practice imo).

2024-03-17 19:44 UTC, Morazzer commented on src/main/java/de/yggdrasil/core/dal/DAL.java
> +        Dotenv dotenv = Dotenv.configure().load();
I mean you could use `java.util.Properties`

2024-04-01 12:12 UTC, Morazzer approved these changes

2024-04-01 12:12 UTC, merged